"""initial_schema.

Revision ID: 04dc1b8926aa
Revises:
Create Date: 2026-08-09 08:51:00.112236
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "04dc1b8926aa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("watermark", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agents_status", "agents", ["status"], unique=False)
    op.create_table(
        "ai_models",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_models_status", "ai_models", ["status"], unique=False)
    op.create_table(
        "processing_history",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("event", sa.String(length=120), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_processing_history_entity",
        "processing_history",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "agent_configs",
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("model_settings", sa.JSON(), nullable=False),
        sa.Column("scoring_rules", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", name="uq_agent_configs_agent_id"),
    )
    op.create_table(
        "video_sources",
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("platform", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
        sa.UniqueConstraint("url", name="uq_video_sources_url"),
    )
    op.create_index(
        "ix_video_sources_agent_id", "video_sources", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_video_sources_content_hash", "video_sources", ["content_hash"], unique=False
    )
    op.create_table(
        "workflows",
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_step", sa.String(length=100), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workflows_status", "workflows", ["status"], unique=False)
    op.create_table(
        "clips",
        sa.Column("source_video_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("file_path", sa.String(length=2048), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_video_id"], ["video_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_clips_status", "clips", ["status"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("segments", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("timestamps", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["video_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transcripts_video_id", "transcripts", ["video_id"], unique=False
    )
    op.create_table(
        "video_analysis",
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("emotion_score", sa.Float(), nullable=True),
        sa.Column("hook_score", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("ai_result", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["video_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_video_analysis_video_id", "video_analysis", ["video_id"], unique=False
    )
    op.create_table(
        "workflow_tasks",
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_tasks_status", "workflow_tasks", ["status"], unique=False
    )
    op.create_table(
        "clip_metadata",
        sa.Column("clip_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hashtags", sa.JSON(), nullable=False),
        sa.Column("platform", sa.String(length=80), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clip_id", name="uq_clip_metadata_clip_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clip_metadata")
    op.drop_index("ix_workflow_tasks_status", table_name="workflow_tasks")
    op.drop_table("workflow_tasks")
    op.drop_index("ix_video_analysis_video_id", table_name="video_analysis")
    op.drop_table("video_analysis")
    op.drop_index("ix_transcripts_video_id", table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index("ix_clips_status", table_name="clips")
    op.drop_table("clips")
    op.drop_index("ix_workflows_status", table_name="workflows")
    op.drop_table("workflows")
    op.drop_index("ix_video_sources_content_hash", table_name="video_sources")
    op.drop_index("ix_video_sources_agent_id", table_name="video_sources")
    op.drop_table("video_sources")
    op.drop_table("agent_configs")
    op.drop_index("ix_processing_history_entity", table_name="processing_history")
    op.drop_table("processing_history")
    op.drop_index("ix_ai_models_status", table_name="ai_models")
    op.drop_table("ai_models")
    op.drop_index("ix_agents_status", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
